import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/page";
import { SessionProvider } from "next-auth/react";
import NextAuthProvider from "./Providers/nextauthProvider";
import Providers from "./Providers/reactProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Route E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
         
         <Providers>

 <NextAuthProvider>
     
   <Navbar/>

   <Toaster position="top-center" /> 
      
        <div className="container">
          {children}
        </div>
        <h2>Footer</h2>

         </NextAuthProvider>

         </Providers>
        
        
       
      </body>
    </html>
  );
}
